name: Pet Analysis Testing
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pandas
          pip install mlxtend
          pip install pgeocode
          pip install math
          pip install seaborn
          pip install matplotlib
          pip install ipython
      - name: Run tests with pytest
        run: pytest 