---
title: "PetData Vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PetData Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Package - petanalysis

This R-package `petanalysis` contains 7 wrapper functions to get pet available data of the US. These functions process API [https://api.petfinder.com/v2/organizations?page=1](https://api.petfinder.com/v2/organizations?page=1e) to get data from shelter information and process API [https://api.petfinder.com/v2/animals?page=1](https://api.petfinder.com/v2/animals?page=1) to get the animal data. One function provide information for shelters and others provide information about animals. This package contains 8 internal functions, 2 for requesting API, 2 for data wrangling for shelter data, and 2 for data wrangling of animal data for association rules, and 2 for building plots which are not available to user. The list of 4 wrapper functions available to user is given below:


```
1. get_shelter(postcode = None)
2. assoc_rules(pets_data_df, min_supp, min_conf, sort_by_col, rule_cnt)
3. visualize()
``` 

The detailed description of these functions as given below.

### To install package

First, user need to install `install.packages("devtools")` and then install the package from github using command `install_github('atevhs/DATA534_PetAnalysis', build_vignettes=TRUE)`. Make the optional argument `build_vignettes` true if you want to build vignettes for this package and use `browseVignettes("PetData")` to see the vignette . Then, the package can be loaded as below:

# ```{r setup}
# library(petanalysis)
# ```

### 1. get_shelter(postcode = None)

This function `get_shelter` returns a dataframe of shelter information of desired district of the US. The function accepts the postcode from the user. If user does not pass any argument then it would prompt a box for user to pass the postcode. The postcode for the US is five digit number, the function would validate the passed input. The returned data is a data frame and contains the columns including the id, name, phone, website and the postcode. The function can be called as below. 


```
get_shelter(postcode = None)

```


### 2. assoc_rules(pets_data_df, min_supp, min_conf, sort_by_col, rule_cnt)

This function `assoc_rules` returns a dataframe of association analysis result. The function accepts 5 arguments from the user to activate the function in mlxtend package. The function can be called as below. 


```
assoc_rules(pets_data_df, min_supp, min_conf, sort_by_col, rule_cnt)

```


### 3. visualize()

This function `visualize()` returns a age histogram  or a size heatmap. The function would prompt the user a box to pass their choice. The return age histogram would show the frequency of four age groups; and the size heatmap would show the information for age and size groups of our data. The function can be called as below. 

```
visualize()

```












